services:
  - type: web
    name: instagram-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8385635455:AAGSwcS-fol43Sd2ogy6-5rXgn5cRmOJnT8"
      - key: WEBHOOK_DOMAIN
        value: "https://instagram-bvt4.onrender.com"
