services:
  - type: web
    name: instagram-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8385635455:AAENIQLo1J3npQU-wn0E4l1-NG7NCJH0rJk"
      - key: WEBHOOK_DOMAIN
        value: "https://instagram-bvt4.onrender.com"
